fetch(window.API_URL+'/').then(r=>r.json()).then(d=>{document.getElementById('server-status').innerHTML=`<div class='card'>Backend Connected: ${d.app||'GlobalEarn'} (${d.mode||'online'})</div>`}).catch(()=>{});
const translations={French:{heroTitle:'Courtage Crypto • Forex • Actions',heroText:'Tradez avec des outils premium.',cta:'Ouvrir un compte'},Spanish:{heroTitle:'Broker de Cripto • Forex • Acciones',heroText:'Opera con herramientas premium.',cta:'Abrir cuenta'},Arabic:{heroTitle:'وساطة العملات والأسهم',heroText:'تداول بأدوات احترافية',cta:'فتح حساب'},English:{heroTitle:'Professional Crypto • Forex • Stocks Brokerage',heroText:'Trade with premium tools, trading products and educational resources.',cta:'Open Account'}};
const rates={USD:[1,'$'],EUR:[0.92,'€'],GBP:[0.78,'£'],INR:[83,'₹'],AED:[3.67,'د.إ']};
function updateCurrency(cur){localStorage.setItem('currency',cur);document.querySelectorAll('.price').forEach(el=>{const usd=+el.dataset.usd;el.querySelector('span').textContent=rates[cur][1]+Math.round(usd*rates[cur][0])});document.querySelectorAll('.price-inline').forEach(el=>{const usd=+el.dataset.usd;el.textContent=rates[cur][1]+Math.round(usd*rates[cur][0])})}
function updateLanguage(lang){localStorage.setItem('language',lang);const t=translations[lang];document.getElementById('heroTitle').textContent=t.heroTitle;document.getElementById('heroText').textContent=t.heroText;document.getElementById('cta').textContent=t.cta;}
document.getElementById('currencySwitcher').onchange=e=>updateCurrency(e.target.value);
document.getElementById('languageSwitcher').onchange=e=>updateLanguage(e.target.value);
updateCurrency(localStorage.getItem('currency')||'USD');updateLanguage(localStorage.getItem('language')||'English');
const notes=['Michael explored Gold markets','Emma reviewed crypto charts'];let i=0;setInterval(()=>{const p=document.getElementById('popup');p.style.display='block';p.innerHTML='<strong>Live Activity</strong><p>'+notes[i%notes.length]+'</p>';i++;setTimeout(()=>p.style.display='none',3000)},6000)
